version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies..
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm start
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.js
    - package.json
    - public/*
    - cloud/*