version: 0.2

phases:
  install:
    commands:
      - npm install pm2 -g && pm2 update
      - yum install nginx -y
  pre_build:
    commands:
      - npm ci /opt/deschutesdesigngroup/apps/parse/package.json
  build:
    commands:
      - service nginx start
      - pm2 start /opt/deschutesdesigngroup/apps/parse/process.yml --env production

artifacts:
  files:
    - target/parse-server-1.0-SNAPSHOT.jar
    - appspec.yml