version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - npm install -g npm@latest
      - npm install pm2 -g && pm2 update
      - yum install nginx -y
      - npm install -g n
      - n latest
  pre_build:
    commands:
      - npm install package.json
      - cp nginx.conf /etc/nginx/conf.d
  build:
    commands:
      - nginx -g "server_names_hash_bucket_size 128;"
      - pm2 start process.yml --env production

artifacts:
  files:
    - parse-server-1.0-snapshot.jar
    - appspec.yml