version: 0.2

phases:
  pre_build:
    commands:
      - npm install pm2 -g && pm2 update
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - pm2 start process.yml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'